/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.quarto.view;

import br.com.ifba.quarto.controller.QuartoIController;
import br.com.ifba.quarto.ennum.EstadoQuarto;
import br.com.ifba.quarto.entity.Quarto;
import br.com.ifba.quarto.ennum.TipoQuarto;
import java.math.BigDecimal;
import javax.swing.DefaultComboBoxModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */

@Component
public class QuartoAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuartoAdicionar.class.getName());

    /**
     * Creates new form QuartoAdicionar
     */
    
    @Autowired
    private QuartoIController quartoControler;

    public QuartoAdicionar(QuartoIController quartoControoler) {
        this.quartoControler = quartoControler;
        
        initComponents(); 
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(TipoQuarto.values()));
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(EstadoQuarto.values()));
        
    }
    
    private QuartoListar telaPrincipal;
    
    void setTelaPrincipal(QuartoListar telaPrincipal){
        this.telaPrincipal = telaPrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuartoTexto = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JTextField();
        lblPrecoDiaria = new javax.swing.JLabel();
        txtPrecoDiaria = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblQuartoTexto.setText("Adicionar um Quarto");

        lblNumero.setText("Numero");

        lblTipo.setText("Tipo do Quarto");

        lblQuantidade.setText("Capacidade");

        lblPrecoDiaria.setText("Preco Diaria");

        btnSalvar.setText("Adicionar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        lblEstado.setText("Estado do Quarto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(lblQuartoTexto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecoDiaria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero)
                            .addComponent(txtCapacidade)
                            .addComponent(txtPrecoDiaria)
                            .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQuartoTexto)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoDiaria)
                    .addComponent(txtPrecoDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnSalvar)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String numero = txtNumero.getText().trim();
        TipoQuarto tipo = (TipoQuarto) cbTipo.getSelectedItem();
        int qtd = Integer.parseInt(txtCapacidade.getText().trim());
        BigDecimal preco = new BigDecimal(txtPrecoDiaria.getText());
        EstadoQuarto estado = (EstadoQuarto) cbEstado.getSelectedItem();
        Quarto novoQuarto = new Quarto();
        
        novoQuarto.setNumero(numero);
        novoQuarto.setTipo(tipo);
        novoQuarto.setCapacidade(qtd);
        novoQuarto.setPrecoDiaria(preco);
        novoQuarto.setEstado(estado);
        
        quartoControler.save(novoQuarto);
        
        if (this.telaPrincipal != null) {
                this.telaPrincipal.adicionarLinhaNaTabela(novoQuarto); 
            }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<EstadoQuarto> cbEstado;
    private javax.swing.JComboBox<TipoQuarto> cbTipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrecoDiaria;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuartoTexto;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecoDiaria;
    // End of variables declaration//GEN-END:variables
}
