/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.quarto.view;

import br.com.ifba.hotel.controller.HotelIController;
import br.com.ifba.hotel.entity.Hotel;
import br.com.ifba.quarto.controller.QuartoIController;
import br.com.ifba.quarto.ennum.EstadoQuarto;
import br.com.ifba.quarto.entity.Quarto;
import br.com.ifba.quarto.ennum.TipoQuarto;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */

@Component
@Lazy
public class QuartoAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuartoAdicionar.class.getName());

    /**
     * Creates new form QuartoAdicionar
     */
    
    @Autowired
    private QuartoIController quartoControler;
    
    @Autowired
    private HotelIController otel;
    
    public QuartoAdicionar() {
        initComponents();
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(TipoQuarto.values()));
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(EstadoQuarto.values()));

    }

    
    public void carregarHoteis() {
        List<Hotel> hoteis = otel.findAll();

        cbHotel.removeAllItems();
        for (Hotel h : hoteis) {
            cbHotel.addItem(h);
        }
    }

    
    private QuartoListar telaPrincipal;
    
    void setTelaPrincipal(QuartoListar telaPrincipal){
        this.telaPrincipal = telaPrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuartoTexto = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JTextField();
        lblPrecoDiaria = new javax.swing.JLabel();
        txtPrecoDiaria = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        cbHotel = new javax.swing.JComboBox<>();
        lblOtel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblQuartoTexto.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblQuartoTexto.setText("Adicionar um Quarto");

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setText("Número: ");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo do Quarto");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidade.setText("Capacidade");

        lblPrecoDiaria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecoDiaria.setText("Preco Diaria");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setText("Adicionar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("Estado do Quarto");

        lblOtel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        lblOtel.setText("Hotel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantidade)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrecoDiaria, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCapacidade)
                                        .addComponent(cbTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblQuartoTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblPrecoDiaria))))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOtel)
                            .addComponent(lblEstado)
                            .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblQuartoTexto)
                .addGap(18, 18, 18)
                .addComponent(lblNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblQuantidade)
                .addGap(18, 18, 18)
                .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrecoDiaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecoDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblOtel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
         String numero = txtNumero.getText().trim();
        TipoQuarto tipo = (TipoQuarto) cbTipo.getSelectedItem();
        int qtd = Integer.parseInt(txtCapacidade.getText().trim());
        BigDecimal preco = new BigDecimal(txtPrecoDiaria.getText());
        EstadoQuarto estado = (EstadoQuarto) cbEstado.getSelectedItem();
        Hotel hotelSelecionado = (Hotel) cbHotel.getSelectedItem();

        if (hotelSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um hotel");
            return;
        }

        Quarto novoQuarto = new Quarto();
        novoQuarto.setNumero(numero);
        novoQuarto.setTipo(tipo);
        novoQuarto.setCapacidade(qtd);
        novoQuarto.setPrecoDiaria(preco);
        novoQuarto.setEstado(estado);
        novoQuarto.setHotel(hotelSelecionado);

        quartoControler.save(novoQuarto);
        JOptionPane.showMessageDialog(rootPane, "Quarto salvo com sucesso!");
        if (this.telaPrincipal != null) {
            this.telaPrincipal.carregarQuartos();
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<EstadoQuarto> cbEstado;
    private javax.swing.JComboBox<Hotel> cbHotel;
    private javax.swing.JComboBox<TipoQuarto> cbTipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblOtel;
    private javax.swing.JLabel lblPrecoDiaria;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuartoTexto;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecoDiaria;
    // End of variables declaration//GEN-END:variables
}
