/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.reserva.view;

import br.com.ifba.infrastructure.windowmanager.WindowManager;
import br.com.ifba.reserva.entity.Reserva;
import br.com.ifba.reserva.service.ReservaService;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author crisl
 */
@Component
@Lazy
public class TelaListarReservas extends javax.swing.JFrame {
    
    @Autowired
    private WindowManager windowManager;
    @Autowired
    private ReservaService reservaService;
    public TelaListarReservas() {
        initComponents();
        configurarAcoesTabela();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tabelaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        // Verifica se foi clique duplo (2 cliques)
        if (evt.getClickCount() == 2) {
            int row = tabelaReservas.getSelectedRow();
            if (row != -1) {
                // 1. Pega o ID da reserva da linha selecionada (coluna 0)
                Long id = (Long) tabelaReservas.getValueAt(row, 0);
                
                // 2. Busca o objeto completo (ou passa o ID para o WindowManager)
                // Aqui você usa o seu Controller/Service
                Reserva selecionada = reservaService.findById(id);
                
                // 3. Abre a tela de detalhes via WindowManager
                windowManager.setReservaSelecionada(selecionada);
                windowManager.navigate(TelaListarReservas.this, TelaDetalhesReserva.class).initReserva();
            }
        }
    }
});
    }
    
    @PostConstruct
    public void init() {
        atualizarTabela();
    }

    private void atualizarTabela() {
        try {
            List<Reserva> reservas = reservaService.listarReservas();
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID Reserva", "Data Entrada", "Data Saída", "Status"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Isso impede que o usuário digite dentro da tabela
                }
            };
            tabelaReservas.setModel(model);

            model.setRowCount(0);

            for (Reserva r : reservas) {
                model.addRow(new Object[]{
                    r.getId(),
                    r.getDataEntrada(),
                    r.getDataSaida(),
                    r.isStatus() ? "ATIVO" : "CANCELADO"
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar reservas: " + e.getMessage());
        }
    }
    
    private void configurarAcoesTabela() {
        tabelaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                // Verifica se foi clique duplo
                if (e.getClickCount() == 2) {
                    int row = tabelaReservas.getSelectedRow();
                    if (row != -1) {
                        // Pega o ID da reserva (assumindo que está na coluna 0)
                        Long idReserva = (Long) tabelaReservas.getValueAt(row, 0);
                    
                        // Busca a reserva completa pelo ID (usando o service que já existe)
                        Reserva reserva = reservaService.findById(idReserva); 

                        if (reserva != null) {
                            // Salva no WindowManager para a próxima tela usar
                            windowManager.setReservaSelecionada(reserva);
                            // Navega para a tela de detalhes (exemplo: TelaDetalheReserva)
                            windowManager.navigate(TelaListarReservas.this, TelaDetalhesReserva.class);
                        }
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReservas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Reservas", "Data Inicio", "Data Fim", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelaReservas);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("LISTAGEM DE RESERVAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaReservas;
    // End of variables declaration//GEN-END:variables
}
