/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.hotel.view;

import br.com.ifba.hotel.controller.HotelIController;
import br.com.ifba.hotel.entity.Hotel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class HotelAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HotelAdicionar.class.getName());

    /**
     * Creates new form HotelAdicionar
     */
    
    @Autowired
    private HotelIController hotelController;
    
    public HotelAdicionar(HotelIController hotelController) {
        this.hotelController = hotelController;
        initComponents();
    }
    
    private HotelLitar telaPrincipal;
    
    void setTelaPrincipal(HotelLitar telaPrincipal){
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastrarHotel = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtClassificacao = new javax.swing.JTextField();
        btnCadastrarHoterl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCadastrarHotel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCadastrarHotel.setText("Cadastrar Novo Hotel");

        lblCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCnpj.setText("CNPJ: ");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome: ");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço: ");

        lblClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClassificacao.setText("Classificação: ");

        btnCadastrarHoterl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrarHoterl.setText("Cadastrar Hotel");
        btnCadastrarHoterl.addActionListener(this::btnCadastrarHoterlActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCnpj)
                                .addComponent(lblNome)
                                .addComponent(lblEndereco)
                                .addComponent(lblClassificacao)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCadastrarHotel)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(btnCadastrarHoterl))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtendereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblCadastrarHotel)
                .addGap(44, 44, 44)
                .addComponent(lblCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClassificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnCadastrarHoterl)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarHoterlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarHoterlActionPerformed
        try {
            String cnpj = txtCnpj.getText();
            String nome = txtNome.getText();
            String endereco = txtendereco.getText();
            int classificacao = Integer.parseInt(txtClassificacao.getText());

            Hotel novoHotel = new Hotel();
            novoHotel.setCnpj(cnpj);
            novoHotel.setNome(nome);
            novoHotel.setEndereco(endereco);
            novoHotel.setClassificacao(classificacao);

            Hotel hotelSalvo = hotelController.save(novoHotel);

            JOptionPane.showMessageDialog(
                this,
                "Hotel " + hotelSalvo.getNome() + " salvo com sucesso!"
            );

            if (telaPrincipal != null) {
                telaPrincipal.adicionarLinhaNaTabela(hotelSalvo);
            }

            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "Classificação deve ser um número.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao salvar Hotel: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace(); // MUITO importante no desenvolvimento
        }
    }//GEN-LAST:event_btnCadastrarHoterlActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarHoterl;
    private javax.swing.JLabel lblCadastrarHotel;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtendereco;
    // End of variables declaration//GEN-END:variables
}
