/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.hotel.view;

import br.com.ifba.hotel.controller.HotelIController;
import br.com.ifba.hotel.entity.Hotel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class HotelAtualizar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HotelAtualizar.class.getName());

    /**
     * Creates new form HotelAtualizar
     */
    
    private Hotel cursoSelecionado;
    
    private HotelLitar telaPrincipal;
    
    
    @Autowired
    private HotelIController hotelISalvar;
    
    public HotelAtualizar(HotelIController hotelISalvar) {
        this.hotelISalvar = hotelISalvar;
        initComponents();
    }
    
    private HotelAtualizar(){
        initComponents();
    }
    
    public HotelAtualizar(HotelLitar telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal; // Armazena a referência
        this.cursoSelecionado = telaPrincipal.getHotelSelecionado();
         // Caso um curso esteja selecionado, preenche as labels com dados antigos
         if(cursoSelecionado != null){
             txtCnpj.setText(cursoSelecionado.getCnpj());
             txtNome.setText(cursoSelecionado.getNome());
             txtEndereco.setText(cursoSelecionado.getEndereco());
             txtClassificacao.setText(String.valueOf(cursoSelecionado.getClassificacao()));
             
        }
    }
    
    public void setHotelSelecionado(br.com.ifba.hotel.entity.Hotel cursoSelecionado) {
        this.cursoSelecionado = cursoSelecionado;

        if (this.cursoSelecionado != null) {
            txtCnpj.setText(cursoSelecionado.getCnpj());
            txtNome.setText(cursoSelecionado.getNome());
            txtEndereco.setText(cursoSelecionado.getEndereco());
            txtClassificacao.setText(String.valueOf(cursoSelecionado.getClassificacao()));
        }
    }
    
    private void salvarEdicao() {
        
        String novoCnpj = txtCnpj.getText();
        String novoNome = txtNome.getText();
        String novoEndereco = txtEndereco.getText();
        int novaClassificacao = Integer.parseInt(txtClassificacao.getText());

        if (novoCnpj.isEmpty() || novoNome.isEmpty() || novoEndereco.isEmpty() || novaClassificacao <= 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }
        
        Hotel hotelSelecionado = new Hotel(); 
        hotelSelecionado.setCnpj(novoCnpj);
        hotelSelecionado.setNome(novoNome);
        hotelSelecionado.setEndereco(novoEndereco);
        hotelSelecionado.setClassificacao(novaClassificacao);
     
        if (hotelISalvar == null) {
            JOptionPane.showMessageDialog(this, "Erro que tira meu sono2");
            return;
        }
        
        Hotel verificar = hotelISalvar.findBycnpj(hotelSelecionado.getCnpj());
        if (verificar != null) {
            
            try{
                hotelISalvar.save(hotelSelecionado);
                JOptionPane.showMessageDialog(this, "Hotel atualizado com SUCESSO!");
                dispose();
            }catch(IllegalArgumentException e){
                
                JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro de validação",
                    JOptionPane.ERROR_MESSAGE
                );
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível atualizar");
            dispose();
        }
     }
    
    public void setTelaPrincipal(br.com.ifba.hotel.view.HotelLitar telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizarHotel = new javax.swing.JButton();
        lblCnpj = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtClassificacao = new javax.swing.JTextField();
        lblAtualizarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAtualizarHotel.setText("Salvar Alteração do Hotel");
        btnAtualizarHotel.addActionListener(this::btnAtualizarHotelActionPerformed);

        lblCnpj.setText("CNPJ");

        lblNome.setText("NOME");

        lblEndereco.setText("ENDERECO");

        lblClassificacao.setText("CLASSIFICACAO");

        txtCnpj.setText("jTextField1");

        txtNome.setText("jTextField2");

        txtEndereco.setText("jTextField3");

        txtClassificacao.setText("jTextField4");

        lblAtualizarCurso.setText("Atualizar Hotel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCnpj))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClassificacao)
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAtualizarHotel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtClassificacao)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(lblAtualizarCurso)))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblAtualizarCurso)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnpj)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassificacao)
                    .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnAtualizarHotel)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarHotelActionPerformed
        // TODO add your handling code here:
            salvarEdicao();
            this.telaPrincipal.carregarHoteis(); 
            this.dispose();
        
    }//GEN-LAST:event_btnAtualizarHotelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarHotel;
    private javax.swing.JLabel lblAtualizarCurso;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
