/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.hotel.view;

import br.com.ifba.hotel.controller.HotelIController;
import br.com.ifba.hotel.entity.Hotel;
import br.com.ifba.infrastructure.viewlistener.HotelAtualizadoListener;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class HotelAtualizar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HotelAtualizar.class.getName());

    /**
     * Creates new form HotelAtualizar
     */
    
    private Hotel hotelSelecionado;
    
    private HotelLitar telaPrincipal;
    
    private HotelAtualizadoListener hotelAtualizadoListener;
    
    
    @Autowired
    private HotelIController hotelISalvar;
    
    public HotelAtualizar(HotelIController hotelISalvar) {
        this.hotelISalvar = hotelISalvar;
        initComponents();
    }
    
    private HotelAtualizar(){
        initComponents();
    }
    
    public HotelAtualizar(HotelLitar telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal; // Armazena a referência
        this.hotelSelecionado = telaPrincipal.getHotelSelecionado();
         // Caso um curso esteja selecionado, preenche as labels com dados antigos
         if(hotelSelecionado != null){
             txtCnpj.setText(hotelSelecionado.getCnpj());
             txtNome.setText(hotelSelecionado.getNome());
             txtEndereco.setText(hotelSelecionado.getEndereco());
             txtClassificacao.setText(String.valueOf(hotelSelecionado.getClassificacao()));
             
        }
    }
    
    public void setHotelSelecionado(br.com.ifba.hotel.entity.Hotel cursoSelecionado) {
        this.hotelSelecionado = cursoSelecionado;

        if (this.hotelSelecionado != null) {
            txtCnpj.setText(cursoSelecionado.getCnpj());
            txtNome.setText(cursoSelecionado.getNome());
            txtEndereco.setText(cursoSelecionado.getEndereco());
            txtClassificacao.setText(String.valueOf(cursoSelecionado.getClassificacao()));
        }
    }
    
    public void setHotelAtualizadoListener(HotelAtualizadoListener listener) {
        this.hotelAtualizadoListener = listener;
    }
    
    
    private void salvarEdicao() {
        
        String novoCnpj = txtCnpj.getText();
        String novoNome = txtNome.getText();
        String novoEndereco = txtEndereco.getText();
        int novaClassificacao = Integer.parseInt(txtClassificacao.getText());

        if (novoCnpj.isEmpty() || novoNome.isEmpty() || novoEndereco.isEmpty() || novaClassificacao <= 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }
        
        Hotel hotelSelecionado = new Hotel(); 
        hotelSelecionado.setCnpj(novoCnpj);
        hotelSelecionado.setNome(novoNome);
        hotelSelecionado.setEndereco(novoEndereco);
        hotelSelecionado.setClassificacao(novaClassificacao);
     
        if (hotelISalvar == null) {
            JOptionPane.showMessageDialog(this, "Erro que tira meu sono2");
            return;
        }
        
        Hotel verificar = hotelISalvar.findBycnpj(hotelSelecionado.getCnpj());
        if (verificar != null) {
            
            try{
                hotelISalvar.save(hotelSelecionado);
                if (hotelAtualizadoListener != null) {
                    hotelAtualizadoListener.onHotelAtualizado();
                }
                JOptionPane.showMessageDialog(this, "Hotel atualizado com SUCESSO!");
                dispose();
            }catch(IllegalArgumentException e){
                
                JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro de validação",
                    JOptionPane.ERROR_MESSAGE
                );
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível atualizar");
            dispose();
        }
     }
    
    public void setTelaPrincipal(br.com.ifba.hotel.view.HotelLitar telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizarHotel = new javax.swing.JButton();
        lblCnpj = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtClassificacao = new javax.swing.JTextField();
        lblAtualizarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 593));

        btnAtualizarHotel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizarHotel.setText("Salvar Alteração do Hotel");
        btnAtualizarHotel.addActionListener(this::btnAtualizarHotelActionPerformed);

        lblCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCnpj.setText("CNPJ: ");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome: ");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço: ");

        lblClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClassificacao.setText("Classificação: ");

        lblAtualizarCurso.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblAtualizarCurso.setText("Atualizar Dados do Hotel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCnpj)
                            .addComponent(lblAtualizarCurso)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndereco)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClassificacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnAtualizarHotel)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblAtualizarCurso)
                .addGap(18, 18, 18)
                .addComponent(lblCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClassificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnAtualizarHotel)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarHotelActionPerformed
        // TODO add your handling code here:
            salvarEdicao(); 
            this.dispose();
        
    }//GEN-LAST:event_btnAtualizarHotelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarHotel;
    private javax.swing.JLabel lblAtualizarCurso;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
