/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.hotel.view;

import br.com.ifba.hotel.controller.HotelIController;
import br.com.ifba.hotel.entity.Hotel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class HotelAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HotelAdicionar.class.getName());

    /**
     * Creates new form HotelAdicionar
     */
    
    @Autowired
    private HotelIController hotelController;
    
    public HotelAdicionar(HotelIController hotelController) {
        this.hotelController = hotelController;
        initComponents();
    }
    
    private HotelLitar telaPrincipal;
    
    void setTelaPrincipal(HotelLitar telaPrincipal){
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastrarHotel = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtClassificacao = new javax.swing.JTextField();
        btnCadastrarHoterl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCadastrarHotel.setText("Cadastrar novo Hotel");

        lblCnpj.setText("CNPJ");

        lblNome.setText("NOME");

        lblEndereco.setText("ENDEREÇO");

        lblClassificacao.setText("CLASSIFICACAO");

        btnCadastrarHoterl.setText("Cadastrar Hotel");
        btnCadastrarHoterl.addActionListener(this::btnCadastrarHoterlActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblCadastrarHotel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCnpj)
                                    .addGap(92, 92, 92)
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNome)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEndereco)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClassificacao)
                                .addGap(18, 18, 18)
                                .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnCadastrarHoterl)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCadastrarHotel)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnpj)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassificacao))
                .addGap(70, 70, 70)
                .addComponent(btnCadastrarHoterl)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarHoterlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarHoterlActionPerformed
        // TODO add your handling code here:
        String cnpj = txtCnpj.getText();
        String nome = txtNome.getText();
        String endereco = txtendereco.getText();
        int classificacao = Integer.parseInt(txtClassificacao.getText());
        
        //Hotel novoHotel = new Hotel(cnpj, nome, endereco, classificacao);
        
        Hotel hotelSalvo = new Hotel();

        try {
            
           // this.hotelController.save(novoHotel);
            hotelSalvo = this.hotelController.findBycnpj(txtCnpj.getText());
          
            JOptionPane.showMessageDialog(this, "Curso " + hotelSalvo.getNome() + " Salvo com sucesso!");

            
            if (this.telaPrincipal != null) {
                this.telaPrincipal.adicionarLinhaNaTabela(hotelSalvo); 
            }

        }catch (Exception e) {
            // Erros inesperados
            JOptionPane.showMessageDialog(this, 
                "Ocorreu um erro inesperado ao salvar o curso.", 
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        } finally {
                txtClassificacao.setText("");
                txtCnpj.setText("");
                txtNome.setText("");
                txtendereco.setText("");
                dispose();
          }
    }//GEN-LAST:event_btnCadastrarHoterlActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarHoterl;
    private javax.swing.JLabel lblCadastrarHotel;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtendereco;
    // End of variables declaration//GEN-END:variables
}
