/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.cliente.view;

import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.reserva.controller.ReservaIController;
import br.com.ifba.reserva.entity.Reserva;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author raiii
 */
public class AdicionarReserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdicionarReserva.class.getName());

    /**
     * Creates new form AdicionarReserva
     */
    private final Cliente cliente;
    private final ReservaIController reservaIController;
    private DetalhesCliente telaDetalhes;

    public AdicionarReserva(Cliente cliente, ReservaIController reservaIController, DetalhesCliente telaDetalhes) {
        this.cliente = cliente;
        this.reservaIController = reservaIController;
        this.telaDetalhes = telaDetalhes;
       
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Adicionar Reserva");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorTotal = new javax.swing.JLabel();
        lblDataEntrada = new javax.swing.JLabel();
        lblDataSaida = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        txtDataEntrada = new javax.swing.JTextField();
        txtDataSaida = new javax.swing.JTextField();
        bntAdicionarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValorTotal.setText("Valor Total: ");

        lblDataEntrada.setText("Data de Entrada: ");

        lblDataSaida.setText("Data de Saída: ");

        txtValorTotal.setText("Digite aqui...");

        txtDataEntrada.setText("Digite aqui...");

        txtDataSaida.setText("Digite aqui...");

        bntAdicionarReserva.setText("Adicionar Reserva");
        bntAdicionarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataSaida)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataSaida))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataEntrada)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataEntrada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorTotal)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(bntAdicionarReserva)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataEntrada)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataSaida)
                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntAdicionarReserva)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAdicionarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarReservaActionPerformed
        try {
            if (txtValorTotal.getText().trim().isEmpty()
                    || txtDataEntrada.getText().trim().isEmpty()
                    || txtDataSaida.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos.",
                    "Validação",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            double valorTotal = Double.parseDouble(
                txtValorTotal.getText().trim().replace(",", ".")
            );

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            LocalDate dataEntrada = LocalDate.parse(
                txtDataEntrada.getText().trim(),
                formatter
            );

            LocalDate dataSaida = LocalDate.parse(
                txtDataSaida.getText().trim(),
                formatter
            );

            if (dataSaida.isBefore(dataEntrada)) {
                JOptionPane.showMessageDialog(
                    this,
                    "A data de saída deve ser depois da data de entrada.",
                    "Validação",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            Reserva reserva = new Reserva();
            reserva.setValorTotal(valorTotal);
            reserva.setDataEntrada(dataEntrada);
            reserva.setDataSaida(dataSaida);
            reserva.setStatus(true);
            reserva.setCliente(cliente);

            reservaIController.save(reserva);
            telaDetalhes.carregarReservas();

            JOptionPane.showMessageDialog(
                this,
                "Reserva cadastrada com sucesso!"
            );

            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "Valor total inválido.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(
                this,
                "Data inválida. Use o formato dd/MM/yyyy.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao cadastrar reserva: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_bntAdicionarReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionarReserva;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtDataSaida;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
