/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.cliente.view;

import br.com.ifba.cliente.controller.ClienteIController;
import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.infrastructure.util.Utils;
import br.com.ifba.reserva.controller.ReservaIController;
import br.com.ifba.reserva.entity.Reserva;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raiii
 */
public class DetalhesCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetalhesCliente.class.getName());

    /**
     * Creates new form DetalhesCliente
     */
    private Cliente cliente;
    private ClienteIController clienteIController;
    private ListarClientes telaListar;
    private ReservaIController reservaIController;

    public DetalhesCliente(Cliente cliente, ClienteIController clienteIController, ListarClientes telaListar, ReservaIController reservaIController) {
        this.cliente = cliente;
        this.clienteIController = clienteIController;
        this.telaListar = telaListar;
        this.reservaIController = reservaIController;
        
        initComponents();
        
        Utils.aplicarTemaTela(this);
        Utils.estilizarBotao(bntCancelarReserva);
        Utils.estilizarBotao(bntEditar);
        Utils.estilizarBotao(bntExcluir);
        Utils.estilizarBotao(bntReserva);
        configurarTabelaReservas();
        carregarDados();
        carregarReservas();
        setLocationRelativeTo(null);
        setTitle("Detalhes do Cliente");
    }
    
    private void carregarDados() {
        lblNome.setText("Nome: " + cliente.getNome());
        lblCpf.setText("CPF: " + cliente.getCpf());
        lblTelefone.setText("Telefone: " + cliente.getTelefone());
    }

    public void atualizarDados() {
        lblNome.setText("Nome: " + cliente.getNome());
        lblCpf.setText("CPF: " + cliente.getCpf());
        lblTelefone.setText("Telefone: " + cliente.getTelefone());

        if (telaListar != null) {
            telaListar.atualizarTabela();
        }
    }
    
    private void configurarTabelaReservas() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Entrada", "Saída", "Valor", "Status"},
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblListaReserva.setModel(model);
    }
    
    public void carregarReservas() {
        List<Reserva> reservas = reservaIController.findByCliente(cliente.getId());

        DefaultTableModel model = (DefaultTableModel) tblListaReserva.getModel();
        model.setRowCount(0);

        for (Reserva r : reservas) {
            model.addRow(new Object[]{
                r.getId(),
                r.getDataEntrada(),
                r.getDataSaida(),
                r.getValorTotal(),
                r.isStatus() ? "ATIVA" : "CANCELADA"
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        bntEditar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntReserva = new javax.swing.JButton();
        bntCancelarReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaReserva = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setText("Nome: ");

        lblCpf.setText("CPF: ");

        lblTelefone.setText("Telefone: ");

        bntEditar.setText("Editar Cliente");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir Cliente");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        bntReserva.setText("Adicionar Reserva");
        bntReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReservaActionPerformed(evt);
            }
        });

        bntCancelarReserva.setText("Cancelar Reserva");
        bntCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarReservaActionPerformed(evt);
            }
        });

        tblListaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(79, 79, 79)
                                .addComponent(lblCpf)
                                .addGap(109, 109, 109)
                                .addComponent(lblTelefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntEditar)
                                .addGap(18, 18, 18)
                                .addComponent(bntExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(bntCancelarReserva)
                                .addGap(18, 18, 18)
                                .addComponent(bntReserva))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCpf)
                    .addComponent(lblTelefone))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntReserva)
                    .addComponent(bntEditar)
                    .addComponent(bntExcluir)
                    .addComponent(bntCancelarReserva))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        EditarCliente tela = new EditarCliente(cliente, clienteIController, DetalhesCliente.this);
        tela.setVisible(true);
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        int opc = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir este cliente?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
        );

        if (opc == JOptionPane.YES_OPTION) {
            clienteIController.delete(cliente);
            JOptionPane.showMessageDialog(this, "Cliente excluído!");
            dispose(); // fecha a tela de detalhes
        }
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReservaActionPerformed
        AdicionarReserva tela = new AdicionarReserva(cliente, reservaIController, this);
        tela.setVisible(true);
    }//GEN-LAST:event_bntReservaActionPerformed

    private void bntCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarReservaActionPerformed
        int linha = tblListaReserva.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma reserva.");
            return;
        }

        Long idReserva = (Long) tblListaReserva.getValueAt(linha, 0);
        String status = (String) tblListaReserva.getValueAt(linha, 4);

        if ("CANCELADA".equals(status)) {
            JOptionPane.showMessageDialog(this, "Reserva já está cancelada.");
            return;
        }

        int opc = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente cancelar esta reserva?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
        );

        if (opc == JOptionPane.YES_OPTION) {
            reservaIController.cancelarReserva(idReserva);
            carregarReservas();
            JOptionPane.showMessageDialog(this, "Reserva cancelada com sucesso!");
        }
    }//GEN-LAST:event_bntCancelarReservaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelarReserva;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tblListaReserva;
    // End of variables declaration//GEN-END:variables
}
