/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.cliente.view;

import br.com.ifba.cliente.controller.ClienteIController;
import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.infrastructure.util.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author raiii
 */
public class EditarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCliente.class.getName());

    /**
     * Creates new form EditarCliente
     */
    private final Cliente cliente;
    private final ClienteIController clienteIController;
    private final DetalhesCliente telaDetalhes;

    public EditarCliente(
            Cliente cliente,
            ClienteIController clienteIController,
            DetalhesCliente telaDetalhes
    ) {
        this.cliente = cliente;
        this.clienteIController = clienteIController;
        this.telaDetalhes = telaDetalhes;

        initComponents();
        carregarDadosCliente();
        setLocationRelativeTo(null);
        
        Utils.aplicarTemaTela(this);
        Utils.estilizarBotao(bntSalvar);
        setTitle("Editar Dados do Cliente");
    }
    
    private void carregarDadosCliente() {
        txtNovoNome.setText(cliente.getNome());
        txtNovoCpf.setText(String.valueOf(cliente.getCpf()));
        txtNovoEndereco.setText(cliente.getEndereco());
        txtNovoTelefone.setText(cliente.getTelefone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoNome = new javax.swing.JLabel();
        lblNovoCpf = new javax.swing.JLabel();
        lblNovoEndereco = new javax.swing.JLabel();
        lblNovoTelefone = new javax.swing.JLabel();
        txtNovoNome = new javax.swing.JTextField();
        txtNovoCpf = new javax.swing.JTextField();
        txtNovoEndereco = new javax.swing.JTextField();
        txtNovoTelefone = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNovoNome.setText("Nome: ");

        lblNovoCpf.setText("CPF: ");

        lblNovoEndereco.setText("Endereço: ");

        lblNovoTelefone.setText("Telefone: ");

        txtNovoNome.setText("jTextField1");

        txtNovoCpf.setText("jTextField2");

        txtNovoEndereco.setText("jTextField3");

        txtNovoTelefone.setText("jTextField4");

        bntSalvar.setText("Salvar Novos Dados");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNovoTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNovoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNovoEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNovoEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNovoNome)
                                    .addComponent(lblNovoCpf))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNovoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(txtNovoCpf)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(bntSalvar)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoNome)
                    .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoCpf)
                    .addComponent(txtNovoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoEndereco)
                    .addComponent(txtNovoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNovoTelefone)
                    .addComponent(txtNovoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntSalvar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        String nome = txtNovoNome.getText().trim();
        String cpf = txtNovoCpf.getText().trim();
        String endereco = txtNovoEndereco.getText().trim();
        String telefone = txtNovoTelefone.getText().trim();

        if (nome.isEmpty() || cpf.isEmpty() || endereco.isEmpty() || telefone.isEmpty()) {
            Utils.mostrarAviso(this, "Preencha todos os campos obrigatórios.");
            return;
        }

        //  Validação de CPF (somente números)
        if (!cpf.matches("\\d+")) {
            Utils.mostrarErro(this, "CPF deve conter apenas números.");
            return;
        }

        Cliente cliente = new Cliente();
        cliente.setNome(nome);
        cliente.setCpf(cpf);
        cliente.setEndereco(endereco);
        cliente.setTelefone(telefone);

        try {
            clienteIController.save(cliente);

            telaDetalhes.atualizarDados();

            Utils.mostrarSucesso(this, "Cliente cadastrado com sucesso!");

        } catch (RuntimeException e) {
            Utils.mostrarErro(this, e.getMessage());
        }
    }//GEN-LAST:event_bntSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JLabel lblNovoCpf;
    private javax.swing.JLabel lblNovoEndereco;
    private javax.swing.JLabel lblNovoNome;
    private javax.swing.JLabel lblNovoTelefone;
    private javax.swing.JTextField txtNovoCpf;
    private javax.swing.JTextField txtNovoEndereco;
    private javax.swing.JTextField txtNovoNome;
    private javax.swing.JTextField txtNovoTelefone;
    // End of variables declaration//GEN-END:variables
}
