/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.cliente.view;

import br.com.ifba.cliente.controller.ClienteIController;
import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.reserva.controller.ReservaIController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author raiii
 */
@Component
public class ListarClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarClientes.class.getName());

    /**
     * Creates new form ListarClientes
     */
    private TableRowSorter<DefaultTableModel> sorter;
    private DefaultTableModel modelo;
    @Autowired
    private ClienteIController clienteIController;
    private ReservaIController reservaIController;
    public ListarClientes(ClienteIController clienteIController, ReservaIController reservaIController) {
        this.clienteIController = clienteIController;
        this.reservaIController = reservaIController;

        initComponents();
        criarModeloTabela();
        configurarTabela();
        configurarAcoesTabela();
        corrigirScroll();
        atualizarTabela();

        setTitle("Listagem de Clientes");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        bntAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        txtPesquisar.setText("Pesquise aqui...");

        bntAdicionar.setText("Cadastrar");
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntAdicionar)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
        CadastrarCliente tela = new CadastrarCliente(clienteIController, ListarClientes.this);
        tela.setVisible(true);
    }//GEN-LAST:event_bntAdicionarActionPerformed
    private void criarModeloTabela() {
        String[] colunas = {"ID", "Nome", "CPF", "Endereço", "Telefone"};

        modelo = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // tabela agora é só visualização
            }
        };

        tblClientes.setModel(modelo);
    }
    public void configurarTabela() {

        // 1) Impede redimensionamento automático
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        // 2) OCULTA a coluna ID (índice 0)
        tblClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(0);

        // 3) Ajusta largura das colunas visíveis
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(220); // Nome
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(140); // CPF
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(220); // Endereço
        tblClientes.getColumnModel().getColumn(4).setPreferredWidth(120); // Telefone

        // 4) Aparência
        tblClientes.setRowHeight(30);
        tblClientes.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12)
        );
        tblClientes.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12)
        );
    }

    
    private void configurarAcoesTabela() {

        sorter = new TableRowSorter<>(modelo);
        tblClientes.setRowSorter(sorter);
        
        tblClientes.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {

            if (e.getClickCount() == 2) {

                int row = tblClientes.rowAtPoint(e.getPoint());
                int modelRow = tblClientes.convertRowIndexToModel(row);

                Long id = (Long) modelo.getValueAt(modelRow, 0);
                Cliente cliente = clienteIController.findById(id);

                if (cliente != null) {
                    DetalhesCliente tela =
                        new DetalhesCliente(cliente, clienteIController, ListarClientes.this, reservaIController);
                        tela.setVisible(true);
                }
            }
        }
    });

    // 🔎 FILTRO DE PESQUISA
        txtPesquisar.getDocument().addDocumentListener(
            new javax.swing.event.DocumentListener() {

                @Override
                public void insertUpdate(javax.swing.event.DocumentEvent e) {
                    filtrarTabela();
                }

                @Override
                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    filtrarTabela();
                }

                @Override
                public void changedUpdate(javax.swing.event.DocumentEvent e) {
                    filtrarTabela();
                }
            }
        );
    }
    
    public void atualizarTabela() {

        modelo.setRowCount(0);

        List<Cliente> lista = clienteIController.findAll();

        if (lista != null) {
            for (Cliente c : lista) {
                modelo.addRow(new Object[]{
                    c.getId(),       // coluna 0 (oculta)
                    c.getNome(),     // 1
                    c.getCpf(),      // 2
                    c.getEndereco(),// 3
                    c.getTelefone(),// 4
                });
            }
        }

        tblClientes.revalidate();
        tblClientes.repaint();
    }


    
    private void filtrarTabela() {
        String texto = txtPesquisar.getText().trim();

        if (texto.isEmpty()) {
            sorter.setRowFilter(null); // mostra tudo
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1));
            // (1) é o índice da coluna "Nome"
        }
    }
    
    private void corrigirScroll() {

    // Garante que a tabela esteja SOMENTE no jScrollPane1
    jScrollPane1.setViewportView(tblClientes);

    // Políticas de rolagem corretas
    jScrollPane1.setHorizontalScrollBarPolicy(
        javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
    );
    jScrollPane1.setVerticalScrollBarPolicy(
        javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED
    );

    // Atualiza layout
    jScrollPane1.revalidate();
    jScrollPane1.repaint();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
