/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.dashboard;

import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class DashUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashUsuario.class.getName());

    /**
     * Creates new form DashUsuario
     */
    public DashUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagemReserva = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        lblImagemMinhasReservas = new javax.swing.JLabel();
        btnMinhasReservas = new javax.swing.JButton();
        lblBemVindo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meMenuPrincipal = new javax.swing.JMenu();
        meMeusDados = new javax.swing.JMenuItem();
        meSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(965, 677));

        lblImagemReserva.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        lblImagemReserva.setText("Imagem de reserva");

        btnReservar.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        btnReservar.setText("Reservar");

        lblImagemMinhasReservas.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        lblImagemMinhasReservas.setText("Imagem de Minhas reservas");

        btnMinhasReservas.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        btnMinhasReservas.setText("Minhas Reservas");

        lblBemVindo.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblBemVindo.setText("Seja Bem-Vindo, ");

        jMenuBar1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        meMenuPrincipal.setText("Menu");

        meMeusDados.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        meMeusDados.setText("Meus dados");
        meMenuPrincipal.add(meMeusDados);

        meSobre.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        meSobre.setText("Sobre");
        meMenuPrincipal.add(meSobre);

        jMenuBar1.add(meMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblImagemReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(lblImagemMinhasReservas)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinhasReservas)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblBemVindo)
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagemReserva)
                    .addComponent(lblImagemMinhasReservas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnMinhasReservas))
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinhasReservas;
    private javax.swing.JButton btnReservar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblImagemMinhasReservas;
    private javax.swing.JLabel lblImagemReserva;
    private javax.swing.JMenu meMenuPrincipal;
    private javax.swing.JMenuItem meMeusDados;
    private javax.swing.JMenuItem meSobre;
    // End of variables declaration//GEN-END:variables
}
