/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.dashboard;

import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.cliente.view.AdicionarReservas;
import br.com.ifba.cliente.view.DetalheCliente;
import br.com.ifba.infrastructure.windowmanager.WindowManager;
import br.com.ifba.usuario.entity.Usuario;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class DashUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashUsuario.class.getName());

    /**
     * Creates new form DashUsuario
     */
    
    @Autowired
    private WindowManager windowmanager;
    
    private Usuario user;
    
    public DashUsuario(WindowManager windowmanager) {
        this.windowmanager = windowmanager;
        initComponents();
    }
    
    public void carregarDados(){
        user = windowmanager.getUsuarioSelecionado();
        lblBemVindo.setText("Seja Bem-Vindo(a), " + user.getPessoa().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagemReserva = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        lblImagemMinhasReservas = new javax.swing.JLabel();
        btnMinhasReservas = new javax.swing.JButton();
        lblBemVindo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meMenuPrincipal = new javax.swing.JMenu();
        meMeusDados = new javax.swing.JMenuItem();
        meSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblImagemReserva.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        lblImagemReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pootelimag1 (1).jpg"))); // NOI18N

        btnReservar.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(this::btnReservarActionPerformed);

        lblImagemMinhasReservas.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        lblImagemMinhasReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pootelimag3 (1).jpg"))); // NOI18N

        btnMinhasReservas.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        btnMinhasReservas.setText("Minhas Reservas");
        btnMinhasReservas.addActionListener(this::btnMinhasReservasActionPerformed);

        lblBemVindo.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblBemVindo.setText("Seja Bem-Vindo, ");

        jMenuBar1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        meMenuPrincipal.setText("Menu");

        meMeusDados.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        meMeusDados.setText("Meus dados");
        meMenuPrincipal.add(meMeusDados);

        meSobre.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        meSobre.setText("Sobre");
        meMenuPrincipal.add(meSobre);

        jMenuBar1.add(meMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinhasReservas)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblImagemReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lblImagemMinhasReservas)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImagemMinhasReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBemVindo)
                        .addGap(116, 116, 116)
                        .addComponent(lblImagemReserva)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnMinhasReservas))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinhasReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinhasReservasActionPerformed
        // TODO add your handling code here:
        DetalheCliente dash = windowmanager.navigate(this, DetalheCliente.class);
        windowmanager.setUsuarioSelecionado(user);
        dash.initCliente();
        
        
    }//GEN-LAST:event_btnMinhasReservasActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        windowmanager.setUsuarioSelecionado(user);
        AdicionarReservas dashReserva = windowmanager.navigate(this, AdicionarReservas.class);
        dashReserva.init();
    }//GEN-LAST:event_btnReservarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinhasReservas;
    private javax.swing.JButton btnReservar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblImagemMinhasReservas;
    private javax.swing.JLabel lblImagemReserva;
    private javax.swing.JMenu meMenuPrincipal;
    private javax.swing.JMenuItem meMeusDados;
    private javax.swing.JMenuItem meSobre;
    // End of variables declaration//GEN-END:variables
}
