/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.dashboard;

import org.springframework.stereotype.Component;

/**
 *
 * @author igo
 */
@Component
public class DashFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashFuncionario.class.getName());

    /**
     * Creates new form DashFuncionario
     */
    public DashFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagemServico = new javax.swing.JLabel();
        btnServicos = new javax.swing.JButton();
        lblBemVindo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meMenuPrincipal = new javax.swing.JMenu();
        meMeusDados = new javax.swing.JMenuItem();
        meSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblImagemServico.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        lblImagemServico.setText("Imagem de serviço");

        btnServicos.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        btnServicos.setText("Serviços");

        lblBemVindo.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblBemVindo.setText("Seja Bem-Vindo, ");

        jMenuBar1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        meMenuPrincipal.setText("Menu");

        meMeusDados.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        meMeusDados.setText("Meus dados");
        meMenuPrincipal.add(meMeusDados);

        meSobre.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        meSobre.setText("Sobre");
        meMenuPrincipal.add(meSobre);

        jMenuBar1.add(meMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblBemVindo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(btnServicos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(lblImagemServico)))
                .addGap(147, 366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblBemVindo)
                .addGap(107, 107, 107)
                .addComponent(lblImagemServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnServicos)
                .addGap(164, 164, 164))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServicos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblImagemServico;
    private javax.swing.JMenu meMenuPrincipal;
    private javax.swing.JMenuItem meMeusDados;
    private javax.swing.JMenuItem meSobre;
    // End of variables declaration//GEN-END:variables
}
